[FIREBASE]
json = """
{
  "type": "service_account",
  "project_id": "infosharing-dantdkm",
  "private_key_id": "fc859cb4879252fbd6ba631f8caf200f727d7341",
  "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0B...IDAQAB\\n-----END PRIVATE KEY-----\\n",
  "client_email": "firebase-adminsdk-fbsvc@infosharing-dantdkm.iam.gserviceaccount.com",
  "client_id": "100345651200368567891",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40infosharing-dantdkm.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
